### ISSUE TITLE
Module 'scipy.misc' has no attribute 'imread'

### ISSUE THREAD

**Issue by tykurtz** [lmb-freiburg/netdef-docker#7]
After building and running one of the examples, I receive the error,

```sh
AttributeError: module 'scipy.misc' has no attribute 'imread'
```

Full stack,
```sh
Traceback (most recent call last):
  File "controller.py", line 11, in <module>
    controller.run()
  File "/home/netdef/netdef_slim/tensorflow/controller/base_controller.py", line 36, in run
    self._command_hooks[command]()
  File "/home/netdef/netdef_slim/tensorflow/controller/base_controller.py", line 53, in eval
    state=self._args.state)
  File "/home/netdef/netdef_slim/tensorflow/controller/base_controller.py", line 91, in eval
    output = self.net_actions(net_dir=self.base_path).eval(**kwargs)
  File "/home/netdef/netdef_slim/tensorflow/controller/net_actions.py", line 40, in eval
    if isinstance(image_0, str): image_0=read(image_0).transpose(2, 0, 1)[np.newaxis, :, :, :].astype(np.float32)
  File "/home/netdef/netdef_slim/utils/io.py", line 16, in read
    elif file.endswith('.png'): return readImage(file)
  File "/home/netdef/netdef_slim/utils/io.py", line 166, in readImage
    return misc.imread(name)
AttributeError: module 'scipy.misc' has no attribute 'imread'
```
Looks like [scipy.misc.imread was deprecated in 1.2.0](https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.imread.html) and imageio.imread should be used instead.

This can either be solved by pinning scipy version to something before 1.3, or updating netdef_slim to using imageio.imread

**Comment by nikolausmayer** [comment]
Thanks! Should be fixed in https://github.com/lmb-freiburg/netdef-docker/commit/71d07f9d3f2f1c76b2619ae6e769b325e9c7b058.
